import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Manpreet Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>

      <body className={inter.className}>
        <div className="container w-full overscroll-x-none sm:max-w-full p-4 bg-main-color text-white">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>

      <Script
        src="https://kit.fontawesome.com/78ec4dfdd6.js"
        crossOrigin="anonymous"
      ></Script>
      <Script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></Script>
      <Script src="node_modules/@material-tailwind/html/scripts/collapse.js"></Script>
      <Script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></Script>
    </html>
  );
}
